#!/usr/bin/env python3
"""Serve docs/ locally for UI testing.

Reads .env (BOARDLOG_KNOCK, optional BOARDLOG_ENDPOINT) and writes
docs/site.config.local.js so the gate phrase is pre-filled — you only press
Enter to get past the gate page. The Lambda Function URL is cross-origin from
localhost and will fail CORS; that is expected. Locally the gate opens without
contacting the backend, and you can drive the redesigned dashboard from a CSV
(e.g. data/tension-logbook.csv) via "Load a CSV file instead".

Usage:
    python scripts/serve_local.py
    # then open http://localhost:8000

    python scripts/serve_local.py --write-config-only
    # regenerate docs/site.config.local.js without starting a server
"""
import http.server
import json
import os
import socketserver
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
ENV = ROOT / ".env"
PORT = int(os.environ.get("PORT", "8000"))


def load_env(path):
    values = {}
    if path.exists():
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            values[key.strip()] = val.strip().strip('"').strip("'")
    return values


def write_local_config(env):
    cfg = {}
    if env.get("BOARDLOG_KNOCK"):
        cfg["knock"] = env["BOARDLOG_KNOCK"]
    if env.get("BOARDLOG_ENDPOINT"):
        cfg["endpoint"] = env["BOARDLOG_ENDPOINT"]
    # Keep "</script" from breaking out of the generated <script> element.
    serialized = json.dumps(cfg).replace("</", "<\\/")
    (DOCS / "site.config.local.js").write_text(
        "// Generated by scripts/serve_local.py from .env -- do not commit.\n"
        f"window.BOARDLOG_LOCAL = {serialized};\n",
        encoding="utf-8",
    )
    return cfg


def main():
    env = load_env(ENV)
    cfg = write_local_config(env)

    if "--write-config-only" in sys.argv:
        # Regenerate site.config.local.js from .env and exit without serving.
        # Used by rotation tooling that just needs the prefill refreshed.
        knock_state = "set" if cfg.get("knock") else "NOT set"
        print(f"Wrote {DOCS / 'site.config.local.js'} (gate phrase: {knock_state})")
        return

    os.chdir(DOCS)

    knock_state = "set" if cfg.get("knock") else "NOT set -- add BOARDLOG_KNOCK to .env"
    print(f"Serving {DOCS}")
    print(f"  http://localhost:{PORT}")
    print(f"  gate phrase: {knock_state}")
    print("  (Lambda CORS failures from localhost are expected; use a CSV to test.)")

    class Handler(http.server.SimpleHTTPRequestHandler):
        def end_headers(self):
            # Never cache during dev so edits show up on reload.
            self.send_header("Cache-Control", "no-store")
            super().end_headers()

        def log_message(self, *args):
            pass

    with socketserver.TCPServer(("127.0.0.1", PORT), Handler) as httpd:
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nStopped.")


if __name__ == "__main__":
    main()
